# Generated by Django 3.1.6 on 2021-02-17 19:25

from django.db import migrations, models
import music_room.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=music_room.models.generate_room_code, max_length=50, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('votes_count_to_skip', models.IntegerField(default=1)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
