# Generated by Django 3.1.6 on 2021-02-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ishost',
            field=models.BooleanField(default=False),
        ),
    ]
