# Generated by Django 3.2 on 2021-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='songurl',
            field=models.CharField(default='HpxX4ZE4KWE', max_length=1999),
        ),
    ]
