# Generated by Django 3.2.5 on 2021-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='songurl',
            field=models.CharField(default='NKzd_YiW9AQ', max_length=1999),
        ),
    ]
