# Generated by Django 3.2 on 2021-05-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0002_alter_room_songurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='songurl',
            field=models.CharField(default='FMSU4QDbdew', max_length=1999),
        ),
    ]
