# Generated by Django 3.2 on 2021-05-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0003_alter_room_songurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='songurl',
            field=models.CharField(default='qsUK-BG5OQQ', max_length=1999),
        ),
    ]
