# Generated by Django 3.2.5 on 2021-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0003_alter_room_songurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='songurl',
            field=models.CharField(default='xSWVPqnKcXQ', max_length=1999),
        ),
    ]
