# Generated by Django 3.1.6 on 2021-02-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0002_room_ishost'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
