# Generated by Django 3.1.6 on 2021-02-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
