# Generated by Django 3.1.6 on 2021-02-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0003_room_current_song'),
        ('spotifyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votecount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=500, unique=True)),
                ('song_id', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_room.room')),
            ],
        ),
    ]
